[build]
  base = "/"
  command = "yarn build"
  publish = "build"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]

[[redirects]]
  from = "/careers/head-of-talent/"
  to = "/careers/people-and-talent-acquisition/"

[[redirects]]
  from = "/careers/backend-software-engineer/"
  to = "/careers/core-database-engineer/"
